#!/bin/bash

: <<- COMMENT
To use koi, you need to do three things:
  1. source the koi script
  2. override the 'koiname' variable
  3. override the 'koidescription' variable

To run the script, use the __koirun function at the very end of the script:
  __koirun "$@"
COMMENT

source koi
koiname=curl_example
koidescription="Examples of potential curl commands you could make with koi"

function createuser {
	__addarg "-h" "--help" "help" "optional" "" "Create a new user"
	__addarg "-p" "--port" "storevalue" "optional" "80" "Port where server is running"
	__addarg "-u" "--user" "storevalue" "required" "" "The name of the user to create"
	__parseargs "$@"
	curl -X POST -H "Content-Type: application/json" -d "{\
		\"user\": \"$user\"\
	}" http://localhost:${port}/api/v1/create
}

function run {
	__addarg "-h" "--help" "help" "optional" "" "Run a job/script on the server"
	__addarg "-p" "--port" "storevalue" "optional" "80" "Port where server is running"
	__addarg "-u" "--user" "storevalue" "required" "" "Name of user"
	__addarg "-f" "--folder" "storevalue" "required" "" "Name of folder where script is located"
	__addarg "-s" "--script" "storevalue" "required" "" "Name of script to run"
	__parseargs "$@"
	curl -X POST -H "Content-Type: application/json" -d "{\
		\"user\": \"$user\",\
		\"script\": \"$script\",\
		\"folder\": \"$folder\",\
		\"options\": []\
	}" http://localhost:${port}/api/v1/run
}

function show {
	__addarg "-h" "--help" "help" "optional" "" "List running jobs for a given user"
	__addarg "-p" "--port" "storevalue" "optional" "80" "Port where server is running"
	__addarg "-u" "--user" "storevalue" "required" "" "Name of user"
	__parseargs "$@"
	curl -X POST -H "Content-Type: application/json" -d "{\
		\"user\": \"$user\"\
	}" http://localhost:${port}/api/v1/list
}

# ============ RUN LOGIC ============ #
__koirun "$@"
