#!/bin/bash
# if which coy > /dev/null 2>&1 ; then
# 	source ../coy
# else
# 	source coy
# fi

source ~/personal/coy/coy
coyname=curl_example
coydescription="Examples of potential curl commands you could make with coy"

function createuser {
	__addarg "-h" "--help" "help" "optional" "" ">> $coyname $FUNCNAME\nCreate a new user"
	__addarg "-p" "--port" "storevalue" "optional" "8000" "Port where server is running"
	__addarg "-u" "--user" "storevalue" "required" "" "The name of the user to create"
	__parseargs "$@"
	curl -X POST -H "Content-Type: application/json" -d "{\
		\"user\": \"$user\"\
	}" http://localhost:${port}/api/v1/create
}

function run {
	__addarg "-h" "--help" "help" "optional" "" ">> $coyname $FUNCNAME\nRun a job/script on the server"
	__addarg "-p" "--port" "storevalue" "optional" "8000" "Port where server is running"
	__addarg "-u" "--user" "storevalue" "required" "" "Name of user"
	__addarg "-f" "--folder" "storevalue" "required" "" "Name of folder where script is located"
	__addarg "-s" "--script" "storevalue" "required" "" "Name of script to run"
	__parseargs "$@"
	curl -X POST -H "Content-Type: application/json" -d "{\
		\"user\": \"$user\",\
		\"script\": \"$script\",\
		\"folder\": \"$folder\",\
		\"options\": []\
	}" http://localhost:${port}/api/v1/run
}

function show {
	__addarg "-h" "--help" "help" "optional" "" ">> $coyname $FUNCNAME\nList running jobs for a given user"
	__addarg "-p" "--port" "storevalue" "optional" "8000" "Port where server is running"
	__addarg "-u" "--user" "storevalue" "required" "" "Name of user"
	__parseargs "$@"
	curl -X POST -H "Content-Type: application/json" -d "{\
		\"user\": \"$user\"\
	}" http://localhost:${port}/api/v1/list
}

# ============ RUN LOGIC ============ #
if declare -F -- "${1:-}" >/dev/null ; then
	"$@"
else
	__errortext "$coyname: err: no such command '$1'"
	__errortext "Use 'help' for available commands"
	exit 1
fi
