#!/bin/bash
set -e

: <<- COMMENT
To use koi:
  1. source the koi script
  2. override the 'koiname' variable with the name of your script
  3. override the 'koidescription' variable with the description of your script

To add arguments:
  1. add arguments to each function with __addarg
  2. parse the arguments with __parseargs "$@"

To run the script, use the __koirun function at the very end of the script:
  __koirun "$@"
COMMENT

source koi
koiname=koi_template
koidescription="Helpful template to demonstrate what argument options are available with koi"

# Here's a function that showcases the different options available with koi:
function myfunction {
	# help
	__addarg "-h" "--help" "help" "optional" "" "A helpful documentation message about myfunction"

	# storing values
	__addarg "-a" "--aaa" "storevalue" "required" "" "A required argument"
	__addarg "-b" "--bbb" "storevalue" "optional" "" "An optional argument"
	__addarg "-c" "--ccc" "storevalue" "optional" "default value" "An optional argument with a default value"

	# store arrays
	__addarg "-d" "--ddd" "storearray" "required" "" "An array where at least one value is required"
	__addarg "-e" "--eee" "storearray" "optional" "" "An optional array"

	# paths to files
	__addarg "-f" "--fff" "filepath" "required" "" "A required path to a file"
	__addarg "-g" "--ggg" "filepath" "optional" "" "An optional path to a file"
	__addarg "-h" "--hhh" "filepath" "optional" "/path/to/default.txt" "An optional path to file with a default value"

	# paths to directories
	__addarg "-i" "--iii" "directorypath" "required" "" "A required path to a directory"
	__addarg "-j" "--jjj" "directorypath" "optional" "" "An optional path to a directory"
	__addarg "-l" "--lll" "directorypath" "optional" "/path/to/defaultdir" "An optional path to directory with a default value"

	# flags
	__addarg "-m" "--mmm" "flag" "required" "" "A required flag, which will store 1 if present"
	__addarg "-n" "--nnn" "flag" "optional" "" "An optional flag, which will store 1 if present if included"

	# exit
	__addarg "-o" "--ooo" "exit" "required" "" "A required exit, which will exit"
	__addarg "-p" "--ppp" "exit" "optional" "" "An optional exit, which will exit if included"

	# you need to call __parseargs for arguments to be parsed!
	__parseargs "$@"

	# how to use the arguments you've defined
	echo "storevalue, required: $aaa"
	echo "storeavlue, optional: $bbb"
	echo "storevalue, optional with default value: $ccc"

	echo "storearray, required: ${ddd[@]}"
	echo "storearray, optional: ${eee[@]}"

	echo "filepath, required: $fff"
	echo "filepath, optional: $ggg"
	echo "filepath: optional with default value: $hhh"

	echo "directorypath, required: $iii"
	echo "directorypath, optional: $jjj"
	echo "directorypath, optional with default value: $lll"

	echo "flag, required: $mmm"
	echo "flag, optional: $nnn"

	# TODO: update with positional arguments
}

__koirun "$@"