#!/bin/bash

: <<- COMMENT
To use koi, you need to do three things:
  1. source the koi script
  2. override the 'koiname' variable with the name of your script
  3. override the 'koidescription' variable with the description of your script

To run the script, use the __koirun function at the very end of the script:
  __koirun "$@"
COMMENT

source koi
koiname=koi_template
koidescription="Helpful template"

# ============ CLI FUNCTIONS ============ #

# put your functions here!

# Here's a function that showcases the different options available with koi:
function myfunction {
	# help
	__addarg "-h" "--help" "help" "optional" "" "A helpful documentation message about myfunction"

	# storing values
	__addarg "-a" "--aaa" "storevalue" "required" "" "A required argument"
	__addarg "-b" "--bbb" "storevalue" "optional" "" "An optional argument"
	__addarg "-c" "--ccc" "storevalue" "optional" "default value" "An optional argument with a default value"

	# paths to files
	__addarg "-d" "--ddd" "filepath" "required" "" "A required path to a file"
	__addarg "-e" "--eee" "filepath" "optional" "" "An optional path to a file"
	__addarg "-f" "--fff" "filepath" "optional" "/path/to/default.txt" "An optional path to file with a default value"

	# paths to directories
	__addarg "-g" "--ggg" "directorypath" "required" "" "A required path to a directory"
	__addarg "-h" "--hhh" "directorypath" "optional" "" "An optional path to a directory"
	__addarg "-i" "--iii" "directorypath" "optional" "/path/to/defaultdir" "An optional path to directory with a default value"

	# flags
	__addarg "-j" "--jjj" "flag" "required" "" "A required flag, which will store 1 if present"
	__addarg "-l" "--lll" "flag" "optional" "" "An optional flag, which will store 1 if present if included"

	# exit
	__addarg "-m" "--mmm" "exit" "required" "" "A required exit, which will exit"
	__addarg "-n" "--nnn" "exit" "optional" "" "An optional exit, which will exit if included"

	# you need to call __parseargs for arguments to be parsed!
	__parseargs "$@"
}

# ============ RUN LOGIC ============ #
if declare -F -- "${1:-}" >/dev/null ; then
	"$@"
else
	__errortext "$koiname: err: no such command '$1'"
	__errortext "Use 'help' for available commands"
	exit 1
fi