name: CI
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      shell: bash
      run: |
        echo "Running shellcheck..."
        shellcheck koi
        shellcheck tests/koitest
    - name: tests
      shell: bash
      run: |
        echo "Running tests..."
        cd tests
        ./koitest
